spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: "*********"
    password: "*********"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50


scheduler:
  enabled: false

